-- Create students table
create table students (
  id bigint generated by default as identity primary key,
  name text not null,
  course text,
  marks int,
  created_at timestamp default now()
);

-- Insert data into students
insert into students (name, course, marks)
values
('Ketan Naik', 'MCA', 85),
('Rohit Patil', 'BCA', 78),
('Aarti Deshmukh', 'MCA', 91);

-- Select all records
select * from students;
